name: Cloudformation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs: 
  test-deploy:
    runs-on: ubuntu-latest
    environment: Test
    needs: build
    
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: lambda
          path: artifact
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Deploy to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: challenge-cloudformation
          template: artifact/main.yaml
          no-fail-on-empty-changeset: "1"